export const categories = [
    { name: 'Adspace', image: require('@/assets/images/adspace.png') },
    { name: 'Art', image: require('@/assets/images/art.png') },
    { name: 'Automotive', image: require('@/assets/images/automotive.png') },
    { name: 'Books', image: require('@/assets/images/books.png') },
    { name: 'Clothing', image: require('@/assets/images/clothing.png') },
    { name: 'Collectibles', image: require('@/assets/images/collectibles.png') },
    { name: 'Electronics', image: require('@/assets/images/electronics.png') },
    { name: 'Events', image: require('@/assets/images/events.png') },
    { name: 'Free', image: require('@/assets/images/free.png') },
    { name: 'Gaming', image: require('@/assets/images/gaming.png') },
    { name: 'Gift Cards', image: require('@/assets/images/gift_cards.png') },
    { name: 'Health', image: require('@/assets/images/health.png') },
    { name: 'Home', image: require('@/assets/images/home.png') },
    { name: 'Influencer', image: require('@/assets/images/influencer.png') },
    { name: 'Other', image: require('@/assets/images/other.png') },
    { name: 'Real Estate', image: require('@/assets/images/real_estate.png') },
    { name: 'Services', image: require('@/assets/images/services.png') },
    { name: 'Social', image: require('@/assets/images/social.png') },
    { name: 'Tasks', image: require('@/assets/images/tasks.png') },
    { name: 'Tools', image: require('@/assets/images/tools.png') },
    { name: 'Travel', image: require('@/assets/images/travel.png') },
]; 